on: [push]

jobs:
  check_ingest:
    runs-on: ubuntu-latest
    name: Check elastic pipelines
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check elastic pipelines
      id: check_ingest
      uses: pdreker/elastic-ingest-test-action@master
      with:
        testdir: 'examples'
